# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: build-and-deploy

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B -e package

    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
          host: ${{ secrets.TENCENT_SERVER_HOST }}
          port: ${{ secrets.TENCENT_SERVER_PORT }}
          username: ${{ secrets.TENCENT_SERVER_USERNAME }}
          private_key: ${{ secrets.TENCENT_PRIVATE_KEY }}
          scp_source: ./build/*
          scp_target: /www/wwwroot
          before_script: |
            df -h
          after_script: |
            cd /www/wwwroot
            ls -l
